"""create processed candles

Revision ID: 754d690fb877
Revises: 
Create Date: 2026-08-13 14:34:11.326654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '754d690fb877'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE SCHEMA processed")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exchange', sa.String(length=20), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=20), nullable=False),
    sa.Column('open_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('close_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('high', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('low', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('close', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('volume', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('high >= close', name='check_high_close'),
    sa.CheckConstraint('high >= low', name='check_high_low'),
    sa.CheckConstraint('high >= open', name='check_high_open'),
    sa.CheckConstraint('low <= close', name='check_low_close'),
    sa.CheckConstraint('low <= open', name='check_low_open'),
    sa.CheckConstraint('open_time < close_time', name='check_open_close_time'),
    sa.CheckConstraint('processed_at >= close_time', name='check_processed_at_close_time'),
    sa.CheckConstraint('processed_at >= open_time', name='check_processed_at_open_time'),
    sa.CheckConstraint('volume >= 0', name='check_volume_non_negative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exchange', 'symbol', 'timeframe', 'open_time', name='unique_candle_constraint'),
    schema='processed'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candles', schema='processed')
    op.execute("DROP SCHEMA processed")
    # ### end Alembic commands ###
