"""link processed candles to raw source

Revision ID: f15a560fccb0
Revises: b84f1c2d9e30
Create Date: 2026-09-15 12:20:27.212333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f15a560fccb0'
down_revision: Union[str, Sequence[str], None] = 'b84f1c2d9e30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candles', sa.Column('source_raw_candle_id', sa.Integer(), nullable=False), schema='processed')
    op.create_unique_constraint('uq_processed_candles_source_raw_candle', 'candles', ['source_raw_candle_id'], schema='processed')
    op.create_foreign_key('fk_processed_candles_source_raw_candle', 'candles', 'candles', ['source_raw_candle_id'], ['id'], source_schema='processed', referent_schema='raw', ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_processed_candles_source_raw_candle', 'candles', schema='processed', type_='foreignkey')
    op.drop_constraint('uq_processed_candles_source_raw_candle', 'candles', schema='processed', type_='unique')
    op.drop_column('candles', 'source_raw_candle_id', schema='processed')
    # ### end Alembic commands ###
